spring:
  application:
    name: eureka-server

eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
