spring:
  application:
    name: gateway-server

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lower-case-service-id: true
#     loadbalancer.ribbon.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
