spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sport-organization-service
          uri: lb://SPORT-ORGANIZATION-SERVICE
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: sport-event-service
          uri: lb://SPORT-EVENT-SERVICE
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/event/(?<path>.*), /$\{path}
        # use service discovery as route
    loadbalancer.ribbon.enabled: false

server:
  port: 7072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
